version: 2.1

orbs:
  node: circleci/node@5
  evals: circleci/evals@2.0

jobs:
  build-node:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run build
      - run:
          name: Create the ~/artifacts directory if it doesn't exist
          command: mkdir -p ~/artifacts
      - run:
          name: Copy artifacts
          command: |
            cp -R build dist public .output .next .docusaurus ~/artifacts 2>/dev/null || true
      - store_artifacts:
          path: ~/artifacts
          destination: node-build

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: deploy
          command: "#e.g. ./deploy.sh"
      - run:
          name: found github actions config
          command: ":"

  evals-test-assertions-job:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Generate eval_results.json metrics file
          command: |
            if [ ! -f eval_results.json ]; then
              echo '{}' > eval_results.json
            fi
      - run:
          name: Ensure assertions.json exists
          command: |
            if [ ! -f assertions.json ]; then
              echo '{}' > assertions.json
            fi
      - evals/test:
          assertions: assertions.json
          metrics: eval_results.json
          results: test_results.xml

  update-f1-database:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y postgresql-client unzip curl jq

      - run:
          name: Get latest F1DB release tag
          command: |
            LATEST_RELEASE_TAG=$(curl -s https://api.github.com/repos/f1db/f1db/releases/latest | jq -r .tag_name)
            echo "Ultima release trovata: $LATEST_RELEASE_TAG"
            echo "$LATEST_RELEASE_TAG" > latest_release.txt

      - restore_cache:
          keys:
            - last-release-tag

      - run:
          name: Confronta con release precedente
          command: |
            echo "Confronto con ultima release salvata (se presente)..."
            if [ -f last_release.txt ]; then
              echo "Ultima release precedente trovata: $(cat last_release.txt)"
              if cmp -s last_release.txt latest_release.txt; then
                echo "⏩ Nessuna nuova release, aggiornamento saltato"
                exit 0
              fi
            else
              echo "⚠️ Nessuna release precedente trovata, procedo..."
            fi

      - run:
          name: Download e unzip nuova release
          command: |
            DOWNLOAD_URL=$(curl -s https://api.github.com/repos/f1db/f1db/releases/latest | jq -r '.assets[] | select(.name == "f1db-sql-postgresql.zip") | .browser_download_url')
            echo "Scarico da: $DOWNLOAD_URL"
            curl -L "$DOWNLOAD_URL" -o f1db.zip
            unzip f1db.zip

      - run:
          name: Applica SQL su PostgreSQL
          command: |
            echo "👉 INIZIO ESECUZIONE PSQL"
            SQL_FILE=$(find . -name "f1db-sql-postgresql.sql")
            echo "Trovato file SQL: $SQL_FILE"

            psql "host=$DB_HOST port=$DB_PORT user=$DB_USER dbname=$DB_NAME password=$DB_PASSWORD sslmode=require" \
              -f "$SQL_FILE"

            echo "✅ FINE ESECUZIONE PSQL"
          environment:
            DB_HOST: f1-graphql-db-f1-graphql.c.aivencloud.com
            DB_PORT: 23000
            DB_USER: avnadmin
            DB_NAME: defaultdb

      - run:
          name: Salva nuovo tag release
          command: |
            mv latest_release.txt last_release.txt

      - save_cache:
          key: last-release-tag
          paths:
            - last_release.txt

parameters:
  DB_PASSWORD:
    type: string
    default: ""

workflows:
  build:
    jobs:
      - build-node:
          context:
            - DB Password AIVEN

  test-eval-workflow:
    jobs:
      - evals-test-assertions-job
