name: Update F1 Database

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Every Day at midnight

jobs:
  update-database:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y postgresql-client unzip curl jq

      - name: Get latest F1DB release
        id: get_latest_release
        run: |
          LATEST_RELEASE_URL=$(curl -s https://api.github.com/repos/f1db/f1db/releases/latest | jq -r '.assets[] | select(.name == "f1db-sql-postgresql.zip") | .browser_download_url')
          echo "download_url=$LATEST_RELEASE_URL" >> "$GITHUB_OUTPUT"
          echo "Download URL: $LATEST_RELEASE_URL"

      - name: Download F1DB release
        run: |
          curl -L ${{ steps.get_latest_release.outputs.download_url }} -o f1db.zip
          unzip f1db.zip
          ls -la

      - name: Apply SQL to database
        env:
          PGPASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: f1-graphql-db-f1-graphql.c.aivencloud.com
          DB_PORT: 23000
          DB_USER: avnadmin
          DB_NAME: defaultdb
        run: |
          echo "👉 INIZIO ESECUZIONE PSQL"
          SQL_FILE=$(find . -name "f1db-sql-postgresql.sql")
          echo "Trovato file SQL: $SQL_FILE"

          PGPASSWORD=$PGPASSWORD psql \
            -h $DB_HOST \
            -p $DB_PORT \
            -U $DB_USER \
            -d $DB_NAME \
            -v sslmode=require \
            -f "$SQL_FILE"

          echo "✅ FINE ESECUZIONE PSQL"
